emit:
  - "@typespec/openapi3"
  - "@azure-tools/typespec-ts"
options:
  "@azure-tools/typespec-ts":
    title: NpmRegistryUnofficialClient
    generateMetadata: false
    generateTest: false
    "emitter-output-dir": "{output-dir}"
    packageDetails:
      name: "@jeremymeng/npm-registry-unofficial"
      description: "NPM Registry Client"
      version: "1.0.0-beta.1"