// for ms-rest-js
// export const dependents = [
//   "@azure/ms-rest-nodeauth",
//   "@azure/ms-rest-azure-js",
//   "azure-iothub",
//   "@actions/cache",
//   "@ts-common/azure-js-dev-tools",
//   "oav",
//   "@azure/cognitiveservices-computervision",
//   "@azure/arm-appinsights",
//   "@azure/arm-resourcegraph",
//   "@azure/graph",
//   "@azure/cognitiveservices-luis-authoring",
//   "@azure/batch",
//   "@azure/storage-file",
//   "appcenter-cli",
//   "vscode-azureextensionui",
//   "@azure/cognitiveservices-luis-runtime",
//   "@cloud-carbon-footprint/azure",
//   "@azure/cognitiveservices-translatortext",
//   "@azure/cognitiveservices-qnamaker-runtime",
//   "luis-apis",
//   "@azure/connectors-dynamicsignal",
//   "@azure/connectors-edifact",
//   "@azure/connectors-leaddesk",
//   "@azure/connectors-leankit",
//   "@azure/connectors-faceapi",
//   "@azure/connectors-mailchimp",
//   "@azure/connectors-marketo",
//   "@azure/connectors-msg91forsmstextnvoice",
//   "@azure/connectors-msnweather",
//   "@azure/connectors-gmail",
//   "@azure/connectors-googlecontacts",
//   "@azure/connectors-notiivybrowsernotifications",
//   "@azure/connectors-gototraining",
//   "@azure/connectors-office365outlook",
//   "@azure/connectors-httpwithazuread",
//   "@azure/connectors-imprezian360crm",
//   "@azure/connectors-onenote",
//   "@azure/connectors-pagerduty",
//   "@azure/connectors-postgresql",
//   "@azure/connectors-recordedfuture",
//   "@azure/connectors-linkedinv2",
//   "@azure/connectors-marketingcontenthub",
//   "@azure/connectors-sendmode",
//   "@azure/connectors-servicenow",
//   "@azure/connectors-microsoftforms",
//   "@azure/connectors-microsoftstaffhub",
//   "@azure/connectors-microsoftteams",
//   "@azure/connectors-smtp",
//   "@azure/connectors-onedriveforbusiness",
//   "@azure/connectors-opentextcs",
//   "@azure/connectors-triggercmd",
//   "@azure/connectors-workpoint",
//   "@azure/connectors-zendesk",
//   "@azure/connectors-qnamaker",
//   "@azure/connectors-sage100cloudcompta",
//   "@azure/connectors-serverless360bamtracking",
//   "@azure/connectors-servicebus",
//   "@azure/connectors-teamworkprojects",
//   "@azure/connectors-witivio",
//   "@azure/connectors-ahead",
//   "@azure/connectors-apacheimpala",
//   "@azure/connectors-appointmentscheduling10to8",
//   "@azure/connectors-atbotlogic",
//   "@azure/connectors-azurefilestorage",
//   "@azure/connectors-azuretablestorage",
//   "@azure/connectors-azurevm",
//   "@azure/connectors-commondataservice",
//   "@azure/connectors-amazonredshift",
//   "@azure/connectors-azureappservice",
//   "@azure/connectors-azuremonitorlogs",
//   "@azure/connectors-encodian",
//   "@azure/connectors-basecamp2",
//   "@azure/connectors-bingmaps",
//   "@azure/connectors-blackbaudraisersedgenxt",
//   "@azure/connectors-freshdesk",
//   "@azure/connectors-cloudmersivenlp",
//   "@azure/connectors-commercient",
//   "@azure/connectors-gotowebinar",
//   "@azure/connectors-hipchat",
//   "@azure/connectors-docfusion365",
//   "@azure/cognitiveservices-customvision-prediction",
//   "@azure/connectors-cloudmersivedatavalidation",
//   "@azure/connectors-airslate",
//   "@azure/connectors-cordablockchain",
//   "@azure/connectors-docusign",
//   "@azure/connectors-easyredmine",
//   "@azure/connectors-azureiotcentral",
//   "@azure/connectors-serwersms",
//   "@azure/connectors-shareeffect",
//   "@azure/connectors-slack",
//   "@azure/connectors-surveymonkey",
//   "@azure/connectors-tilkee",
//   "@azure/connectors-vantage365imaging",
//   "@azure/connectors-billspls",
//   "@azure/connectors-bitbucket",
//   "@azure/connectors-bttn",
//   "@azure/connectors-ftp",
//   "@azure/connectors-googledrive",
//   "@azure/connectors-informix",
//   "@azure/connectors-intercom",
//   "@azure/connectors-jira",
//   "@azure/connectors-elasticforms",
//   "@azure/connectors-ethereumblockchain",
//   "@azure/connectors-eventbrite",
//   "@azure/connectors-livechat",
//   "@azure/connectors-microblink",
//   "@azure/connectors-microsofttranslator",
//   "@azure/connectors-microsofttranslatorv2",
//   "@azure/connectors-github",
//   "@azure/connectors-nitro",
//   "@azure/connectors-onedrive",
//   "@azure/connectors-indkycindia",
//   "@azure/connectors-integrablepdf",
//   "@azure/connectors-kintone",
//   "@azure/connectors-pushcut",
//   "@azure/connectors-latinsharedocuments",
//   "@azure/connectors-mailparser",
//   "@azure/connectors-meetingroommap",
//   "@azure/connectors-microsoftdefenderatp",
//   "@azure/connectors-microsofttodo",
//   "@azure/connectors-solyp",
//   "@azure/connectors-muhimbipdf",
//   "@azure/connectors-sparkpost",
//   "@azure/connectors-office365video",
//   "@azure/connectors-trustual",
//   "@azure/connectors-oracledatabase",
//   "@azure/connectors-outlook",
//   "@azure/connectors-uservoice",
//   "@azure/connectors-webexteams",
//   "@azure/connectors-wordpress",
//   "@azure/connectors-x12",
//   "@azure/connectors-pitneybowesdatavalidation",
//   "@azure/connectors-powerbi",
//   "@azure/connectors-projectumpresentit",
//   "@azure/connectors-pureleads",
//   "@azure/connectors-appfigures",
//   "@azure/connectors-appsforopstimeline",
//   "azure-maps-rest",
//   "@a11ywatch/mav",
//   "@azure/connectors-act",
//   "@azure/connectors-adobecreativecloud",
//   "@azure/connectors-axtensioncontentgate",
//   "@azure/connectors-casper365",
//   "@azure/connectors-agilite",
//   "@azure/connectors-authentiselineitem",
//   "@azure/connectors-linkedin",
//   "@azure/connectors-livetilesbots",
//   "@azure/connectors-flowforma",
//   "@azure/connectors-formrecognizer",
//   "@azure/connectors-microsoftschooldatasync",
//   "@azure/connectors-office365groups",
//   "@azure/connectors-harvest",
//   "@azure/connectors-outlookcustomermanager",
//   "@azure/connectors-indpayables",
//   "@azure/connectors-infusionsoft",
//   "@azure/connectors-instapaper",
//   "@azure/connectors-plumsailhelpdesk",
//   "@azure/connectors-plumsailsp",
//   "@azure/connectors-knowledgelake",
//   "@azure/connectors-kusto",
//   "@azure/connectors-latinshareshppermissions",
//   "@azure/connectors-rencorecode",
//   "@azure/connectors-salesforce",
//   "@azure/connectors-medium",
//   "@azure/connectors-sftpssh",
//   "@azure/connectors-motawordtranslations",
//   "@azure/connectors-mtargetsms",
//   "@azure/connectors-sqlserver",
//   "@azure/connectors-survey123",
//   "@azure/connectors-textanalytics",
//   "@azure/connectors-opentextedocs",
//   "@azure/connectors-parsuer",
//   "@azure/connectors-pdf4me",
//   "@azure/connectors-pinterest",
//   "@azure/connectors-xooablockchaindatabase",
//   "@azure/connectors-plumsaildocuments",
//   "@azure/connectors-redmine",
//   "@azure/connectors-rss",
//   "@azure/connectors-sage100cloudvente",
//   "@azure/connectors-shorturl",
//   "@azure/connectors-sproketpoweractions",
//   "@azure/connectors-tallyfy",
//   "@azure/connectors-ventipixassetandinventory",
//   "@azure/applicationinsights-query",
//   "@azure/connectors-authentiseorder",
//   "@azure/connectors-azurecontainerinstance",
//   "@azure/connectors-elasticocr",
//   "@azure/connectors-entegrationsinvoicing",
//   "@azure/connectors-bingsearch",
//   "@azure/connectors-filesystem",
//   "@azure/connectors-biztalkserver",
//   "@azure/connectors-firetext",
//   "@azure/connectors-fulcrum",
//   "@azure/connectors-ciscowebexmeetings",
//   "@azure/connectors-cloudpkimanagement",
//   "@azure/connectors-contentmoderator",
//   "@azure/connectors-derdacksignl4",
//   "@azure/connectors-ibm3270",
//   "@azure/connectors-industrialappstore",
//   "@azure/connectors-dynamics365forfinops",
//   "@azure/connectors-latinshareshpmanagement",
//   "@azure/connectors-eventhubs",
//   "@azure/arm-datalake-analytics",
//   "@azure/arm-operations",
//   "@azure/cognitiveservices-websearch",
//   "@azure/connectors-excelonline",
//   "@azure/connectors-mandrill",
//   "@azure/connectors-partnercenterreferrals",
//   "@azure/connectors-pivotaltracker",
//   "@azure/connectors-politemail",
//   "@azure/connectors-riskiq",
//   "@azure/connectors-linkmobility",
//   "@azure/connectors-scriveesign",
//   "@azure/connectors-seektable",
//   "@azure/connectors-shiftsformicrosoftteams",
//   "@azure/connectors-signinghub",
//   "@azure/connectors-slascone",
//   "@azure/connectors-mitto",
//   "@azure/connectors-mobilyws",
//   "@azure/connectors-mysql",
//   "@azure/connectors-nexmo",
//   "@azure/connectors-ticketingevents",
//   "@azure/connectors-todoist",
//   "@azure/connectors-parserr",
//   "@azure/connectors-partnercenterevents",
//   "@azure/connectors-planner",
//   "@azure/connectors-xooablockchainsmartcontract",
//   "@azure/connectors-plivo",
//   "@azure/connectors-zenkraft",
//   "@azure/connectors-prioritymatrix",
//   "@azure/connectors-sftp",
//   "@azure/connectors-sharepoint",
//   "@azure/connectors-smslink",
//   "@azure/connectors-stormboard",
//   "@azure/connectors-stripe",
//   "@azure/connectors-trello",
//   "@azure/connectors-txtsync",
//   "@azure/connectors-aweber",
//   "@azure/connectors-azureadidentityprotection",
//   "@azure/connectors-azuredevops",
//   "@azure/connectors-azureloganalyticsdatacollector",
//   "@azure/connectors-bitly",
//   "@azure/connectors-campfire",
//   "@azure/connectors-acumatica",
//   "@azure/connectors-amazonsqs",
//   "@azure/connectors-atbotadmin",
//   "@azure/connectors-data8",
//   "@azure/connectors-dynamics365customerinsights",
//   "@azure/connectors-azurecosmosdb",
//   "@azure/connectors-azuredatalake",
//   "@azure/connectors-dynamicsnav",
//   "@azure/connectors-easyvistaselfhelp",
//   "@azure/connectors-azurekeyvault",
//   "@azure/connectors-emfluencemarketingplatform",
//   "@azure/connectors-envoy",
//   "@azure/connectors-exghtsgendocumentnmore",
//   "@azure/connectors-computervisionapi",
//   "@azure/connectors-gotomeeting",
//   "@azure/connectors-contentconversion",
//   "@azure/connectors-hellosign",
//   "@azure/connectors-cpqsync",
//   "@azure/connectors-inoreader",
//   "@azure/connectors-freshbooks",
//   "@azure/connectors-freshservice",
//   "@azure/connectors-hotprofile",
//   "@azure/cognitiveservices-qnamaker",
//   "vscode-azurekudu",
//   "@azure/cognitiveservices-contentmoderator",
//   "@azure/cognitiveservices-customvision-training",
//   "@azure/connectors-ally",
//   "@azure/connectors-as2",
//   "@azure/connectors-twitter",
//   "@azure/connectors-webmerge",
//   "@azure/connectors-wordonlinebusiness",
//   "@azure/connectors-pipedrive",
//   "@azure/connectors-regolinkforclarityppm",
//   "@azure/connectors-sap",
//   "@azure/connectors-telesignsms",
//   "@azure/connectors-tractionguest",
//   "@azure/connectors-xpertdoc",
//   "@azure/connectors-azureautomation",
//   "@azure/connectors-azureblobstorage",
//   "@azure/connectors-azureloganalytics",
//   "@azure/connectors-basecamp",
//   "@azure/connectors-blogger",
//   "@azure/connectors-box",
//   "@azure/connectors-capsulecrm",
//   "@azure/connectors-chatter",
//   "@azure/connectors-cognitoforms",
//   "@azure/connectors-customvision",
//   "@azure/connectors-db2",
//   "@azure/connectors-azureapplicationinsights",
//   "@azure/connectors-dnboptimizer",
//   "@azure/connectors-dynamics365",
//   "@azure/connectors-azuredatafactory",
//   "@azure/connectors-dynamics365salesinsights",
//   "@azure/connectors-azureeventgridpublish",
//   "@azure/connectors-excelonlineonedrive",
//   "@azure/connectors-businesscentral",
//   "@azure/connectors-gofileroom",
//   "@azure/connectors-googlecalendar",
//   "@azure/connectors-googlesheets",
//   "@azure/connectors-d7sms",
//   "@azure/connectors-houseraterqa",
//   "@azure/connectors-dropbox",
//   "@azure/connectors-dynamics365customervoice",
//   "@azure/connectors-instagram",
//   "@azure/connectors-junglemail365",
//   "@azure/connectors-eduframe",
//   "@azure/connectors-facebook",
//   "@azure/connectors-forcamforcebridge",
//   "@azure/connectors-getmyinvoices",
//   "@azure/connectors-infobip",
//   "@azure/connectors-luis",
//   "@azure/connectors-signrequest",
//   "@azure/connectors-skypeforbusinessonline",
//   "@azure/connectors-smarp",
//   "@azure/connectors-smartsheet",
//   "@azure/connectors-mq",
//   "@azure/connectors-soft1",
//   "@azure/connectors-office365groupsmail",
//   "@azure/connectors-teradata",
//   "@azure/connectors-office365users",
//   "azurite",
//   "@azure/arm-sqlvirtualmachine",
//   "@powerbi-cli/powerbi-cli",
//   "@trulive/sye-tools",
//   "@easyapis/easyapis-amazonsqs",
//   "@easyapis/easyapis-azureautomation",
//   "@easyapis/easyapis-azuredatafactory",
//   "@easyapis/easyapis-azureloganalyticsdatacollector",
//   "@easyapis/easyapis-documentdb",
//   "@easyapis/easyapis-dynamicscrmonline",
//   "@easyapis/easyapis-keyvault",
//   "@easyapis/easyapis-office365",
//   "@easyapis/easyapis-outlook",
//   "@easyapis/easyapis-planner",
//   "@easyapis/easyapis-salesforce",
//   "@easyapis/easyapis-sharepointonline",
//   "@easyapis/easyapis-teams",
//   "timfpark-storage-blob",
//   "one-sdk",
//   "@foxmn/azure-database",
//   "@chkimes/actions-cache",
//   "@azure/arm-locks-profile-hybrid-2019-03-01",
//   "@azure/cognitiveservices-formrecognizer",
//   "hsolve",
//   "azure-connectors",
//   "azure-iot-digitaltwins-service",
//   "github-actions.cache-s3",
//   "@azure/cognitiveservices-autosuggest",
//   "@azure/cognitiveservices-customimagesearch",
//   "@azure/arm-servicemap",
//   "@ubicloud/cache",
//   "@azbake/ingredient-app-insights",
//   "@olympeio-extensions/azure",
//   "@useblacksmith/cache",
//   "@azure/arm-commitmentplans",
//   "@naveego/client-auth",
//   "swagger-parameters-extractor",
//   "@easyapis/easyapis-applicationinsights",
//   "@easyapis/easyapis-azurecommunicationservicessms",
//   "@easyapis/easyapis-azuredatalake",
//   "@easyapis/easyapis-cognitiveservicestextanalytics",
//   "@easyapis/easyapis-excelonlinebusiness",
//   "@easyapis/easyapis-gmail",
//   "@easyapis/easyapis-onedriveforbusiness",
//   "@easyapis/easyapis-sap",
//   "@easyapis/easyapis-twitter",
//   "@easyapis/easyapis-webcontents",
//   "vscode-azureextensiondev",
//   "tocapilibraryts",
//   "wechaty-qnamaker",
//   "@dinohorvat/azure-db",
//   "@zhenglaizhang/oav",
//   "@azure/arm-network-profile-2019-03-01-hybrid",
//   "@azure/arm-resources-profile-hybrid-2019-03-01",
//   "@azure/arm-storage-profile-2019-03-01-hybrid",
//   "@azure/cognitiveservices-anomalydetector",
//   "@azure/arm-dns-profile-2019-03-01-hybrid",
//   "botserver",
//   "botbuilder-skills",
//   "connectors-dropbox",
//   "connectors-sdk",
//   "@cache-nix-action/cache",
//   "@azure/cognitiveservices-newssearch",
//   "@azure/cognitiveservices-textanalytics",
//   "@azure/loganalytics",
//   "@azure/arm-batchai",
//   "ado-test-history",
//   "or-msteams-v2",
//   "@azure/arm-commerce",
//   "@martijnhols/actions-cache",
//   "@streetcred.id/service-clients",
//   "@easyapis/easyapis-aci",
//   "@easyapis/easyapis-commondataservice",
// ];

// for core-http
export const dependents = [
  "botbuilder",
  "botframework-connector",
  "botbuilder-ai",
  "oav",
  "backfill-config",
  "@azure/digital-twins-core",
  "fx-api",
  "botbuilder-azure-blobs",
  "backfill-cache",
  "@azure/mixed-reality-authentication",
  "autorest-typescript",
  "dw-autorest-typescript",
  "@azure/core-arm",
  "azure-iot-provisioning-service-with-proxy",
  "@autorest/typescript",
  "autorest-typescript-compat",
  "dw-typescript-codegen",
  "lemon-core-v4-azure",
  "@azure/communication-network-traversal",
  "@autorest/azure-functions-typescript",
  "@azure/opentelemetry-exporter-azure-monitor",
  "@azure/mixedreality-authentication",
  "ado-test-history",
  "@azure/template",
  "botbuilder-jhontsouth",
  "@azure/ai-metrics-advisor",
  "@azure/digitaltwins",
  "@azure/iot-device-update",
  "@azure/quantum-jobs",
  "@marygao/typescript",
  "teamsdev-client",
  "@audc/applicationinsights",
  "microsoft.marketplace.metering",
  "@azure/ai-anomaly-detector",
  "@wipefest/api-sdk",
  "@cloudgraph/cg-provider-azure",
  "@azure/communication-administration",
  "@azure/digital-twins",
  "@azure/search",
  "@azure/synapse-monitoring",
  "@azure/storage-blob-changefeed",
];
